S="ACAAGGAACTCAATAATTACATGATGCGCGCTAGAGAATGTGAGCCGTTAGTTGTGAGACGAATCTGGAAACTGATTGCGACGGAGTTGAAAACGATACGACGGACTGAGAATACGTTTTCTTCAAATTGTAGGTATGGATGGCATTTCCCAGAACtagg"

for i in range(len(S)-41):
    print(S[i:41+i] )