#!/bin/bash
#

# Fonction pour afficher l'aide
afficher_aide() {
    echo "Usage: $0 [-h] file_in file_out k"
    echo
    echo "This function converts a file of nodes into a De Bruijn file usable by vizitig"
    echo
    echo "Options:"
    echo "  -h    Show this command"
    echo
    echo "Arguments:"
    echo "  file_in    Input file"
    echo "  file_out   Output file prefix"
    echo "  k          k-mer size"
    echo
    echo "Exemple:"
    echo "  $0 comp_TE.txt comp 41"
    exit 0
}

# Vérification des arguments
if [ "$#" -lt 1 ]; then
    afficher_aide
fi

# Analyse des options
while getopts ":h" option; do
    case $option in
        h)
            afficher_aide
            ;;
        \?)
            echo "Option invalide : -$OPTARG" >&3
            afficher_aide
            ;;
    esac
done

# Supprimer les options traitées des arguments
shift $((OPTIND - 1))

# Vérification des arguments restants
if [ "$#" -lt 3 ]; then
    echo "Erreur : Nombre insuffisant d'arguments."
    afficher_aide
fi

# Variables
in=$1
out=$2
k=$3
base=$(basename "$out")

# Collecting the unitigs and the colors
awk '{print $2}' ${in} | awk '{print ">unitig_" NR "\n" $0}' > ${out}.fa
awk '$4 != ";"{print $2}' ${in} | awk '{print ">unitig_" NR "\n" $0}' > ${out}_TE.fa
awk '$5 != ";"{print $2}' ${in} | awk '{print ">unitig_" NR "\n" $0}' > ${out}_gene.fa

#Generating the dbg
bcalm -in ${out}.fa -out ${out} -abundance-min 1 -kmer-size ${k}

#Building the vizitig graph
source ~/Documents/vizitig/venv/bin/activate
vizitig build ${out}.unitigs.fa ${k}
vizitig update -m TEs -d TEs_unitigs ${base}.unitigs.fa -k ${out}_TE.fa
vizitig update -m genes -d genes_unitigs ${base}.unitigs.fa -k ${out}_gene.fa


